# Generated by Django 4.2.3 on 2024-06-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_image_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('upload_date', models.DateTimeField()),
                ('original_name', models.CharField(max_length=200)),
                ('filename', models.CharField(default='', max_length=200)),
                ('thumb_frame', models.IntegerField(default=0)),
            ],
        ),
    ]
